language: python
python:
  - "3.6"
env:
  - DJANGO_VERSION='>=1.8,<1.9'
  - DJANGO_VERSION='>=1.11,<1.12'
  - DJANGO_VERSION='>=2.2,<2.3'
install:
  - "pip install Django$DJANGO_VERSION"
  - "pip install -e ."
script:
  - "./runtests.py"
